### ISSUE TITLE
Review 2.0

### ISSUE THREAD

**Issue by theaspect** [Danil42Russia/GoodLine-App#2]
1. main exitCodes опустить вниз к месту первого использования и не разделять объявление и присвоение
2. src/ru/danil42russia/aaa/SHA256.kt:12 зачем тут 0 в строке. Нужно подробное описание алгоритма
3. ru.danil42russia.aaa.domain.ExitCodes элементы не соответствуют coding conventions
4. src/ru/danil42russia/aaa/service/BusinessLogic.kt:8 Javadoc оформляется при помощи /** */ ну и напиши нормальное описание
5. src/ru/danil42russia/aaa/service/BusinessLogic.kt:10 UserService должен передаваться через конструктор (буква D в SOLID)
6. isEditCode непонятно что делает, вообще пиши комментарии
7. энум ExitCodes в единственном числе должен быть
8. src/ru/danil42russia/aaa/service/CmdService.kt:42 непонятно зачем там вообще вложенность, парсишь строку и раскладываешь в cmd
9. Для парсинга даты используй современные методы https://stackoverflow.com/questions/22463062/how-to-parse-format-dates-with-localdatetime-java-8
10. зачем разбито объявление и вызов метода? src/ru/danil42russia/aaa/service/CmdService.kt:70
11. неиспользуемый метод src/ru/danil42russia/aaa/service/CmdService.kt:78

**Comment by Danil42Russia** [comment]
- [x] 1 2a355652d9b98f51918174d11597f8ad703ad24c
- [x] 2 0f93b8d5e6c79e0b776543ccd75eae1813df4b8e, 086ad75d745c5d78a00e815b5ae41c7869d1c415
- [x] 3 73fc4fa7ae3278e7238cc0127ff23d63d1b31d80, cbbd220302baf8faeb0a6a51f8bf9f2e14b5924c
- [x] 4 f1c04797f2e58f9413bf7df944949fbbbf46919f
- [x] 5 cbbd220302baf8faeb0a6a51f8bf9f2e14b5924c
- [x] 6 3450d5f2b78776cfa7a5a43fbfc5d3b55d3921ed
- [x] 7 a408d1073ee48c1b0df1888fb273c333bf5ebe0e
- [x] 8 48a60961a281363eab93ee2a58c06761e63b3cde
- [x] 9 812e9608fef28aa16da8a12e718f931bfb642509
- [x] 10 14cdf79281f1607efb9c1957e13f2fc37dab47a5
- [x] 11 8c08c81712143e7b2c9fbe1ee099d307246f28ed

Прочее:
1. 7719d7eea7b1b52671cd82c15dfb5fe0263e92c6 - Вернул openjdk11
2. ead9830188bc36fd7c2a191c0a369212df4ba40a - Вынес добавление параметров из функции parse, т.к. добавление параметров не должно зависеть, от вызова parse
3. 247c2ea0bdb0f4d2149d86b39d877edca2091e64 - Добавил описание функции через javadoc
4. 1172577493afa73c638a40f17ca0168c3fbddb38 - Изменил название параметра на более правильный и логичный
5. 4400462132ebd850b414ef850f589617ae220d9c - Добавил описание функции через javadoc
6. 75d15ddf227a2f8c952623d90eff408fd2185926 - Изменил название параметров на более правильные и логичные

**Comment by Danil42Russia** [comment]
Забыл указать номер issue в коммите, но что-бы не ломать хронологию изменения, оставлю ссылку на коммит 
[Rename all exit-code in code](https://github.com/Danil42Russia/GoodLine-App/commit/cbbd220302baf8faeb0a6a51f8bf9f2e14b5924c) [:white_check_mark:](https://github.com/Danil42Russia/GoodLine-App/runs/106080034)

**Comment by Danil42Russia** [comment]
Забыл указать номер issue в коммите, но что-бы не ломать хронологию изменения, оставлю ссылку на коммит 
[add javadoc to the fun SHA256 + refactoring](https://github.com/Danil42Russia/GoodLine-App/commit/0f93b8d5e6c79e0b776543ccd75eae1813df4b8e) [:white_check_mark:](https://github.com/Danil42Russia/GoodLine-App/runs/109706568)
